### ISSUE TITLE
Number of threads metered twice

### ISSUE THREAD

**Issue by swerner0** [mweirauch/micrometer-jvm-extras#116]
I noticed my prometheus exports had 2 thread counts listed:
```
# HELP process_threads The number of process threads
# TYPE process_threads gauge
process_threads 486.0
```
and
```
# HELP process_memory_threads_bytes  
# TYPE process_memory_threads_bytes gauge
process_memory_threads_bytes 486.0
```

The last one appears to be from the following:

https://github.com/mweirauch/micrometer-jvm-extras/blob/4c5017c0fd37b7fcbe09c38110cf8df50e8e89af/src/main/java/io/github/mweirauch/micrometer/jvm/extras/ProcessMemoryMetrics.java#L41

Where `KEY.values()` contains the memory values and `THREADS`

**Comment by mweirauch** [comment]
Oops, how embarassing! Thanks for spotting and reporting this! I was seeing this the other day, but thought it was some actual experimental code I worked on quite a while ago in a testing project.

This was introduced with `0.2.0`. I will try to come up with a fix and a release tomorrow evening.

**Comment by swerner0** [comment]
Cool, thanks. 

Yeah, no rush. Our grafana dashboards use the proper value, but did a double take when I saw the other one :-)

**Comment by mweirauch** [comment]
Release `0.2.2` has been synced to Maven Central. Thanks again for reporting!
