### ISSUE TITLE
Native memory tracking

### ISSUE THREAD

**Issue by glandais-eptica** [mweirauch/micrometer-jvm-extras#37]
I've releases a NMT metrics binder on https://github.com/glandais-eptica/nmt-metrics

It might be great to include it in your project. Feel free to help yourself or ask for support.

**Comment by mweirauch** [comment]
Thanks for the heads-up!

I wouldn't include it in this project though. It can be used additionally when required, as NMT has its performance penalties itself and the query implementation as I see it relies on a JDK being present (`jcmd`).
